### ISSUE TITLE
An error while building nuproj projects.

### ISSUE THREAD

**Issue by hmemcpy** [AArnott/pinvoke#182]
I'm getting the following exception on my machine:

```
Error   MSB4018 The "ReadPdbSourceFiles" task failed unexpectedly.
System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {3BFCEA48-620F-4B6B-81F7-B9AF75454C7D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NuProj.Tasks.PdbReader.ReadSourceFiles(String pdbPath) in C:\git\nuproj\src\NuProj.Tasks\ReadPdbSourceFiles.cs:line 36
   at NuProj.Tasks.ReadPdbSourceFiles.Execute() in C:\git\nuproj\src\NuProj.Tasks\ReadPdbSourceFiles.cs:line 25
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() MSCorEE.NuGet   C:\Users\hmemcpy\.nuget\packages\NuProj\0.10.27-beta-g2363d7cd98\tools\NuProj.targets   963 
```

This happens for every nuproj project. Perhaps this is more of a question/issue for the nuproj repo...

Windows 10, VS2015. Any ideas?

**Comment by hmemcpy** [comment]
Hmm, I don't seem to have `msdia*.dll` on my machine, which this guid seems to belong to.

**Comment by AArnott** [comment]
I get lots of results for `msdia*.dll` when I recursively search from `c:\program files (x86)\`. Have you searced there?

```
c:\Program Files (x86)>dir /s msdia*.dll /b
c:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\12.0\Debugger\target\armv4i\MSDIA120.dll
c:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\12.0\Debugger\target\x86\MSDIA120.dll
c:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\14.0\Debugger\target\armv4i\MSDIA140.dll
c:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\14.0\Debugger\target\x64\MSDIA140.dll
c:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\14.0\Debugger\target\x86\MSDIA140.dll
c:\Program Files (x86)\Common Files\Microsoft Shared\VC\amd64\msdia80.dll
c:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Packages\Debugger\msdia120.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\msdia120.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\ClientDiagnostics\MemoryProfiler\DataModel\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\ClientDiagnostics\MemoryProfiler\x86\msdia120.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\msdia140typelib_clr0200.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\x64\msdia140typelib_clr0200.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Platform\DiagnosticsHub\amd64\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Platform\DiagnosticsHub\x86\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x86\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Packages\Debugger\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Packages\Debugger\X64\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\DIA SDK\bin\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\DIA SDK\bin\amd64\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\DIA SDK\bin\arm\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Dynamic Code Coverage Tools\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Dynamic Code Coverage Tools\amd64\msdia140.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64\msdia120.dll
c:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64\msdia140.dll
c:\Program Files (x86)\MSBuild\Microsoft\.NetNative\arm\ilc\tools\msdia120.dll
c:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\tools\msdia120.dll
c:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\tools\msdia120.dll
c:\Program Files (x86)\Windows Kits\10\App Certification Kit\msdia120.dll
c:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\msdia140.dll
```

Given that VS is what seems to offer this DLL, you might try 'repairing' your VS installation.

**Comment by hmemcpy** [comment]
Oh, my bad! Turns out [Everything](https://www.voidtools.com/) (which is generally great), doesn't automatically do wildcard searches, so my search for "MSDIA" didn't get me any valid results.

Yeah, I have tons of MSDIA110,120 and 140 dlls...

**Comment by AArnott** [comment]
Well, 'repairing' your VS installation is still the only idea I have.

**Comment by iosiginer** [comment]
Had the same problem as @hmemcpy, and repairing the installation didn't change anything.
Any other ideas?

**Comment by AArnott** [comment]
We're not using NuProj in this repo any more, @iosiginer. How are you seeing this?
