### ISSUE TITLE
GetWindowText (user32)

### ISSUE THREAD

**Issue by lxman** [AArnott/pinvoke#436]
Receive  "The specified procedure could not be found" when attempting to use GetWindowText(IntPtr hwnd)

**Comment by Lakritzator** [comment]
I'm not a maintainer on this repository, but I'm pretty sure the first question would be for you to supply more information.

For all they know, you could be calling this on a linux environment.

So maybe you can describe the context in which you get this error? Like what dotnet version and where you are running this?

**Comment by AArnott** [comment]
Yes, also a full callstack and exception type + Message. GetWindowText(IntPtr) is a helper method, and it calls into other methods that appear to have the right p/invoke signatures. So we definitely need more info.

**Comment by lxman** [comment]
So, initial info
This is .NET 4.8 on Windows 10
Error follows:

PInvoke.Win32Exception
  HResult=0x80004005
  Message=The specified procedure could not be found
  Source=PInvoke.User32
  StackTrace:
   at PInvoke.User32.GetWindowText(IntPtr hWnd)
   at Controller.WinAPICommon.<>c__DisplayClass0_0.<GetDesktopWindows>g__filter|0(IntPtr hWnd, IntPtr lParam) in C:\Users\michael\source\repos\AutoItTest\Controller\WinAPICommon.cs:line 20
   at PInvoke.User32.EnumDesktopWindows(SafeDesktopHandle hDesktop, WNDENUMPROC lpfn, IntPtr lParam)
   at Controller.WinAPICommon.GetDesktopWindows() in C:\Users\michael\source\repos\AutoItTest\Controller\WinAPICommon.cs:line 31
   at Controller.WinAPICommon.FindWindowByString(String name) in C:\Users\michael\source\repos\AutoItTest\Controller\WinAPICommon.cs:line 37
   at Controller.Controller..ctor() in C:\Users\michael\source\repos\AutoItTest\Controller\Controller.cs:line 13
   at Controller.Program.Main() in C:\Users\michael\source\repos\AutoItTest\Controller\Program.cs:line 19

**Comment by AArnott** [comment]
I can't repro this. If you can send repro code I will take another look.
